/**
 * Generates geometry JSON data in TreeMesh format (GEO_SPEC.md)
 *
 * Vertex layout: perimeter order — for each ring j, all `segments` points.
 * Vertex index = j * segments + i.
 *
 * Each ring of the cylinder is generated by evaluating a circular spline
 * (control points on the circle) at uniform parameter values. The spline
 * operator (centripetal Catmull-Rom) is used in the output expression.
 */

function zigzagEncode(n) {
  return n >= 0 ? n * 2 : -n * 2 - 1;
}

function riceEncode(arr, k) {
  const bits = [];

  for (const signed of arr) {
    const value = zigzagEncode(signed);
    const quotient = value >> k;
    const remainder = value & ((1 << k) - 1);

    for (let i = 0; i < quotient; i++) bits.push(1);
    bits.push(0);
    for (let i = k - 1; i >= 0; i--) bits.push((remainder >> i) & 1);
  }

  while (bits.length % 8 !== 0) bits.push(0);

  const bytes = new Uint8Array(bits.length / 8);
  for (let i = 0; i < bytes.length; i++) {
    let byte = 0;
    for (let j = 0; j < 8; j++) byte = (byte << 1) | bits[i * 8 + j];
    bytes[i] = byte;
  }

  let binary = '';
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

function encodeInt32(arr) {
  const int32 = new Int32Array(arr);
  const bytes = new Uint8Array(int32.buffer);
  let binary = '';
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

function encodeFloat32(arr) {
  const f32 = new Float32Array(arr);
  const bytes = new Uint8Array(f32.buffer);
  let binary = '';
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

function createCylinderData() {
  const radius = 0.5;
  const height = 1.0;
  const segments = 16;   // points around circumference (= number of control points for the ring spline)
  const rings = 5;       // height levels
  const tScale = 1024;   // quantization scale for spline t parameter
  const posScale = 256;  // quantization scale for positions

  // --- Control points for a ring spline ---
  // A ring at height y has `segments` control points equally spaced on a circle.
  // We encode one set of control points per ring (all rings have the same shape,
  // just different y). The spline is evaluated at t = [0, 1, 2, ..., segments-1]
  // to recover the ring vertices.
  //
  // Control points: index i -> angle = i/segments * 2*PI
  // Position: (y, cos(angle)*radius, sin(angle)*radius)  [x=axis, y/z=radial]
  //
  // For the spline to wrap correctly, the first control point is repeated at
  // the end, making the ring periodic with `segments+1` control points where
  // cp[segments] = cp[0].

  const buffers = {};
  const ringSplineExprs = [];   // for vertices interleave
  const ringNSplineExprs = [];  // for normals interleave

  // t buffer: uniform query params [0, 1, 2, ..., segments-1], shared across all rings.
  // Quantized with tScale, stored as raw int32 (k=0).
  const tValues = [];
  for (let i = 0; i < segments; i++) tValues.push(Math.round(i * tScale));
  buffers['ring_t'] = { k: 0, data: encodeInt32(tValues), length: segments };

  for (let j = 0; j < rings; j++) {
    const y = -height / 2 + (height * j / (rings - 1));

    // Control points for ring j: segments+1 points (last = first, for wrap)
    const cpx = [], cpy = [], cpz = [];
    const cnx = [], cny = [], cnz = [];
    for (let i = 0; i <= segments; i++) {
      const angle = (i / segments) * Math.PI * 2;
      cpx.push(Math.round(y             * posScale));
      cpy.push(Math.round(Math.cos(angle) * radius * posScale));
      cpz.push(Math.round(Math.sin(angle) * radius * posScale));
      cnx.push(0);
      cny.push(Math.round(Math.cos(angle) * posScale));
      cnz.push(Math.round(Math.sin(angle) * posScale));
    }
    const ncp = segments + 1;

    // Delta-encode x and z within the ring (smooth curve → small deltas).
    // y is constant per ring, stored absolute.
    const delta = (arr) => arr.map((v, i) => v - (i === 0 ? 0 : arr[i - 1]));

    buffers[`ring${j}_cp_x`] = { k: 2, data: riceEncode(delta(cpx), 2), length: ncp };
    buffers[`ring${j}_cp_y`] = { k: 0, data: encodeInt32(cpy), length: ncp };
    buffers[`ring${j}_cp_z`] = { k: 2, data: riceEncode(delta(cpz), 2), length: ncp };
    buffers[`ring${j}_cn_x`] = { k: 0, data: encodeInt32(cnx), length: ncp };
    buffers[`ring${j}_cn_y`] = { k: 2, data: riceEncode(delta(cny), 2), length: ncp };
    buffers[`ring${j}_cn_z`] = { k: 2, data: riceEncode(delta(cnz), 2), length: ncp };

    const cpVec3 = (xbuf, ybuf, zbuf) => ({
      op: 'divp2',
      args: [{ op: 'vec3', args: [
        { op: 'cumsum', args: [xbuf] },
        ybuf,
        { op: 'cumsum', args: [zbuf] },
      ]}, 8],
    });

    const tExpr = { op: 'divp2', args: ['ring_t', Math.round(Math.log2(tScale))] };

    ringSplineExprs.push({
      op: 'spline',
      args: [
        cpVec3(`ring${j}_cp_x`, `ring${j}_cp_y`, `ring${j}_cp_z`),
        tExpr,
      ],
    });
    ringNSplineExprs.push({
      op: 'spline',
      args: [
        cpVec3(`ring${j}_cn_x`, `ring${j}_cn_y`, `ring${j}_cn_z`),
        tExpr,
      ],
    });
  }

  // --- Triangle indices ---
  // Perimeter order: vertex index = j * segments + i, wrapping in i.
  const indices = [];
  for (let j = 0; j < rings - 1; j++) {
    for (let i = 0; i < segments; i++) {
      const a = j * segments + i;
      const b = j * segments + (i + 1) % segments;
      const c = (j + 1) * segments + i;
      const d = (j + 1) * segments + (i + 1) % segments;
      indices.push(a, c, b);
      indices.push(b, c, d);
    }
  }

  const indicesI = [], indicesJ = [], indicesK = [];
  let prevI = 0, prevJ = 0, prevK = 0;
  for (let t = 0; t < indices.length; t += 3) {
    indicesI.push(indices[t]     - prevI);
    indicesJ.push(indices[t + 1] - prevJ);
    indicesK.push(indices[t + 2] - prevK);
    prevI = indices[t];
    prevJ = indices[t + 1];
    prevK = indices[t + 2];
  }
  const nTriangles = indices.length / 3;
  buffers['indices_i'] = { k: 2, data: riceEncode(indicesI, 2), length: nTriangles };
  buffers['indices_j'] = { k: 2, data: riceEncode(indicesJ, 2), length: nTriangles };
  buffers['indices_k'] = { k: 2, data: riceEncode(indicesK, 2), length: nTriangles };

  return {
    treemesh: "0.1",
    spline_convention: "reflect",
    buffers,
    outputs: {
      vertices: {
        op: 'interleave',
        args: ringSplineExprs,
      },
      normals: {
        op: 'interleave',
        args: ringNSplineExprs,
      },
      triangles: {
        op: 'triangle',
        args: [
          { op: 'cumsum', args: ['indices_i'] },
          { op: 'cumsum', args: ['indices_j'] },
          { op: 'cumsum', args: ['indices_k'] },
        ],
      },
    },
  };
}

const fs = require('fs');
const path = require('path');

const data = createCylinderData();
const outputPath = path.join(__dirname, '..', 'dist', 'geometry.json');
fs.writeFileSync(outputPath, JSON.stringify(data, null, 2));
console.log('Wrote geometry.json to', outputPath);
