/**
 * Generates geometry JSON data in TreeMesh format (GEO_SPEC.md)
 *
 * Vertex layout: perimeter order — for each ring j, all `segments` points.
 * Vertex index = j * segments + i.
 *
 * Each ring of the cylinder is generated by evaluating a circular spline
 * (control points on the circle) at uniform parameter values. The spline
 * operator (centripetal Catmull-Rom) is used in the output expression.
 */

function zigzagEncode(n) {
  return n >= 0 ? n * 2 : -n * 2 - 1;
}

function riceEncode(arr, k) {
  const bits = [];

  for (const signed of arr) {
    const value = zigzagEncode(signed);
    const quotient = value >> k;
    const remainder = value & ((1 << k) - 1);

    for (let i = 0; i < quotient; i++) bits.push(1);
    bits.push(0);
    for (let i = k - 1; i >= 0; i--) bits.push((remainder >> i) & 1);
  }

  while (bits.length % 8 !== 0) bits.push(0);

  const bytes = new Uint8Array(bits.length / 8);
  for (let i = 0; i < bytes.length; i++) {
    let byte = 0;
    for (let j = 0; j < 8; j++) byte = (byte << 1) | bits[i * 8 + j];
    bytes[i] = byte;
  }

  let binary = '';
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

function encodeInt32(arr) {
  const int32 = new Int32Array(arr);
  const bytes = new Uint8Array(int32.buffer);
  let binary = '';
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

function encodeFloat32(arr) {
  const f32 = new Float32Array(arr);
  const bytes = new Uint8Array(f32.buffer);
  let binary = '';
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

function createCylinderData() {
  const height = 1.0;
  const segments = 16;   // vertices per ring (output resolution)
  const rings = 5;       // height levels
  const ncp = 5;         // control points per ring: 4 on circle + 1 wrap (cp[4]=cp[0])
  const tScale = 1024;   // quantization scale for spline t parameter
  const posScale = 256;  // quantization scale for positions

  // Radius profile: waist shape — full radius at ends, smaller in the middle.
  // rings=5, index 0..4: outer, inner, innermost, inner, outer
  const radii = [0.5, 0.35, 0.25, 0.35, 0.5];

  // --- Control points for a ring spline ---
  // Each ring uses 4 control points at 0°, 90°, 180°, 270° on a circle of
  // the ring's radius, plus cp[4]=cp[0] to close the loop.
  // The spline is queried at t = i/segments * 4  for i in [0, segments).

  const buffers = {};
  const ringSplineExprs = [];   // for vertices interleave
  const ringNSplineExprs = [];  // for normals interleave

  // t buffer: query params mapping segment index to [0, 4), shared across rings.
  const tValues = [];
  for (let i = 0; i < segments; i++) tValues.push(Math.round((i / segments) * 4 * tScale));
  buffers['ring_t'] = { k: 0, data: encodeInt32(tValues), length: segments };

  for (let j = 0; j < rings; j++) {
    const y = -height / 2 + (height * j / (rings - 1));
    const radius = radii[j];

    // 4 control points at 0°, 90°, 180°, 270°, then wrap cp[4]=cp[0]
    const cpx = [], cpy = [], cpz = [];
    const cnx = [], cny = [], cnz = [];
    for (let i = 0; i < ncp; i++) {
      const angle = (i / 4) * Math.PI * 2;  // 4 divisions regardless of ncp
      cpx.push(Math.round(y                    * posScale));
      cpy.push(Math.round(Math.cos(angle) * radius * posScale));
      cpz.push(Math.round(Math.sin(angle) * radius * posScale));
      cnx.push(0);
      cny.push(Math.round(Math.cos(angle) * posScale));
      cnz.push(Math.round(Math.sin(angle) * posScale));
    }

    // Delta-encode x and z (smooth curve → small deltas); y constant per ring.
    const delta = (arr) => arr.map((v, i) => v - (i === 0 ? 0 : arr[i - 1]));

    buffers[`ring${j}_cp_x`] = { k: 2, data: riceEncode(delta(cpx), 2), length: ncp };
    buffers[`ring${j}_cp_y`] = { k: 0, data: encodeInt32(cpy), length: ncp };
    buffers[`ring${j}_cp_z`] = { k: 2, data: riceEncode(delta(cpz), 2), length: ncp };
    buffers[`ring${j}_cn_x`] = { k: 0, data: encodeInt32(cnx), length: ncp };
    buffers[`ring${j}_cn_y`] = { k: 2, data: riceEncode(delta(cny), 2), length: ncp };
    buffers[`ring${j}_cn_z`] = { k: 2, data: riceEncode(delta(cnz), 2), length: ncp };

    const cpVec3 = (xbuf, ybuf, zbuf) => ({
      op: 'divp2',
      args: [{ op: 'vec3', args: [
        { op: 'cumsum', args: [xbuf] },
        ybuf,
        { op: 'cumsum', args: [zbuf] },
      ]}, 8],
    });

    // tScale = 1024 = 2^10, so divp2 exponent = 10
    const tExpr = { op: 'divp2', args: ['ring_t', 10] };

    ringSplineExprs.push({
      op: 'spline',
      args: [
        cpVec3(`ring${j}_cp_x`, `ring${j}_cp_y`, `ring${j}_cp_z`),
        tExpr,
      ],
    });
    ringNSplineExprs.push({
      op: 'spline',
      args: [
        cpVec3(`ring${j}_cn_x`, `ring${j}_cn_y`, `ring${j}_cn_z`),
        tExpr,
      ],
    });
  }

  // --- Triangle indices ---
  // Perimeter order: vertex index = j * segments + i, wrapping in i.
  const indices = [];
  for (let j = 0; j < rings - 1; j++) {
    for (let i = 0; i < segments; i++) {
      const a = j * segments + i;
      const b = j * segments + (i + 1) % segments;
      const c = (j + 1) * segments + i;
      const d = (j + 1) * segments + (i + 1) % segments;
      indices.push(a, c, b);
      indices.push(b, c, d);
    }
  }

  const indicesI = [], indicesJ = [], indicesK = [];
  let prevI = 0, prevJ = 0, prevK = 0;
  for (let t = 0; t < indices.length; t += 3) {
    indicesI.push(indices[t]     - prevI);
    indicesJ.push(indices[t + 1] - prevJ);
    indicesK.push(indices[t + 2] - prevK);
    prevI = indices[t];
    prevJ = indices[t + 1];
    prevK = indices[t + 2];
  }
  const nTriangles = indices.length / 3;
  buffers['indices_i'] = { k: 2, data: riceEncode(indicesI, 2), length: nTriangles };
  buffers['indices_j'] = { k: 2, data: riceEncode(indicesJ, 2), length: nTriangles };
  buffers['indices_k'] = { k: 2, data: riceEncode(indicesK, 2), length: nTriangles };

  return {
    treemesh: "0.1",
    spline_convention: "reflect",
    buffers,
    outputs: {
      vertices: {
        op: 'interleave',
        args: ringSplineExprs,
      },
      normals: {
        op: 'interleave',
        args: ringNSplineExprs,
      },
      triangles: {
        op: 'triangle',
        args: [
          { op: 'cumsum', args: ['indices_i'] },
          { op: 'cumsum', args: ['indices_j'] },
          { op: 'cumsum', args: ['indices_k'] },
        ],
      },
    },
  };
}

const fs = require('fs');
const path = require('path');

const data = createCylinderData();
const outputPath = path.join(__dirname, '..', 'dist', 'geometry.json');
fs.writeFileSync(outputPath, JSON.stringify(data, null, 2));
console.log('Wrote geometry.json to', outputPath);
