on: [push]

name: build

jobs:
  trunk-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown
          override: true

      - uses: Swatinem/rust-cache@v2
      - name: Install Dioxus-CLI
        shell: bash
        run: cargo binstall -y --force dioxus-cli --version=0.5.6

      - uses: jetli/trunk-action@v0.5.0

      - name: Build Project 🎁
        shell: bash
        run: trunk build --release

      - name: upload result
        uses: actions/upload-pages-artifact@v2
        with:
          path: "dist/"

  deploy:
    runs-on: ubuntu-latest
    needs: trunk-build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
        # don't forget to go to the settings/environment and to allow main to push !
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
